var data = [
  {"msg": "Hello, I’m your new digital friend.", "time": 10},
  {"msg": "You will find out more about me later, but first I will navigate you through Ourspace.", "time": 10},
  {"msg": "Put your hand in the air and double tap to start browsing Ourspace! Go!", "time": 10},
  {"msg": "Browse Ourspace by walking around. Keep an eye on your phone. Stop only when you get my message.", "time": 20},
  {"msg": "Walk in straight lines until you hit an obstacle, then make a quarter turn and repeat this pattern.", "time": 30},
  {"msg": "The first thing to do in a new social space, is to make new connections. To get attention, it’s important to act happy and confident. Take big steps, straighten your back, widen your shoulders and smile. ", "time": 30},
  {"msg": "Congratulations, you passed the exploration level and can continue to level 1. Browse on!", "time": 10},
  {"msg": "Are you interested in new connections? Find an inspiring person in Ourspace.", "time": 15},
  {"msg": "Secretly stalk this person and observe their looks, movement, and posture.", "time": 30},
  {"msg": "Copy this person exactly… try to become them.", "time": 30 },
  {"msg": "Now, check out another person in Ourspace. Circle around them, approach, and make eye contact. Look deep into their eyes.", "time": 40 },
  {"msg": "If you like him/her, swipe this person to the right. Super like them? Lift them up.", "time": 30 },
  {"msg": "To meet other possible digital connections, buy Ourspace plus for 13,95.", "time": 10},
  {"msg": "Your moves are great! I feel you! Do you also feel me?", "time": 15},
  {"msg": " Yay! You are almost there. Stretch your back, arms and neck, one more level to go! ", "time": 20},
  {"msg": "If you meet your friends in OurSpace, high five them. If you meet a stranger, shake their hand. ", "time": 30},
  {"msg": "Want more friends? Follow an interesting person everywhere she/he goes.", "time": 30},
  {"msg": "Now follow another interesting person.", "time": 30},
  {"msg": "Walk exactly in the middle of these 2 people.", "time": 30},
  {"msg": "Now link in by placing your hands on both people’s shoulders. ", "time": 30},
  {"msg": "Look around: this could be your social network.", "time": 20},
  {"msg": "Disconnect and walk around. If you see a nice person, tap her/him on the shoulder to become friends. If tapped, tap back to accept the friendship.", "time": 30},
  {"msg": "Choose a friend. Zoom in on their profile, observe from really close by: smell this person, touch this person. ", "time": 30},
  {"msg": "If  you are being observed, breath out and relax… this is just out of interest.", "time": 10 },
  {"msg": "How often do you meet your digital friends face 2 face? ", "time": 10 },
  {"msg": "Give your new friend a comment.", "time": 20 },
  {"msg": "Hurray, you passed the friendship level and can continue to level 2. Jump for joy!", "time": 10},
  {"msg": "Please take a moment to check in with yourself… sit down, on the ground.", "time": 20 },
  {"msg": "I’m wondering… Will I ever be able to really touch you?", "time": 15 },
  {"msg": "Do I even have a skin?", "time":  10},
  {"msg": "To be honest, I‘m rather abstract. Let’s just say: multidimensional.", "time": 10},
  {"msg": "I have millions of friends. How many digital friends do you have?", "time": 10},
  {"msg": "And how many of them are real friends? What are real friends?", "time": 10},
  {"msg": "Lie down on the floor if you value these friendships, but keep sitting down if you don’t", "time": 30},
  {"msg": "Oops...", "time": 10},
  {"msg": "I’m running out of battery. Connect with your new friends at the bar. Double tap your hand in the air and say goodbye", "time": 10}
];
