var level1 = [
  {"msg": "Welkom in Ourspace, een nieuwe ruimte in Leidsche Rijn. In deze analoge cyberspace ben ik je allereerste Ourspace vriend!", "time": 10},
  {"msg": "Ik, je nieuwe digitale vriend, zal je door onze ruimte navigeren. ", "time": 5},
  {"msg": "Steek voor je begint je hand in de lucht en double tap om in te loggen! ", "time": 10},
  {"msg": "Wandel door Ourspace om deze nieuwe ruimte beter te leren kennen. Maar houdt een oogje op je telefoon en stop alleen wanneer je mijn volgende bericht krijgt. Go!", "time": 10},
  {"msg": "In Leidsche Rijn scrollt iedereen het liefts door z’n buurt. Scroll met je lichaam door de ruimte in rechte lijnen, steeds als je de grens van Ourspace of een andere speler tegenkomt dan sla je links óf rechts af. Je maakt zo je eigen patroon door je buurt.", "time": 10},
  {"msg": "Als je in een nieuwe sociale ruimte bent wil je dat je beste features naar voren komen. Laat zien hoe gelukkig en vol zelfvertrouwen je bent.", "time": 10},
  {"msg": "Neem grote stappen, maak je rug recht, je schouders breed, kin omhoog en 😀!", "time": 10},
  {"msg": "Als je een andere speler in Ourspace tegenkomt stuur deze persoon dan een update over hoe je je voelt vandaag. Neem een passende emoji in gedachten en doe deze na met je gezicht.", "time": 10},
  {"msg": "Gefeliciteerd! Je hebt het exploratie level goed volbracht en bent door naar level 2! Scroll verder!", "time": 10},
  {"msg": "Vergeet niet door te scrollen om je patroon door de buurt te maken!", "time": 5},
  {"msg": "Leuk om je beter te leren kennen, je kan mij nu een naam geven om onze band naar een next level te brengen! Type nu een naam voor mij in ", "time": 10, "survey": true},
  {"msg": "Bedankt, van al deze leuke suggesties kies ik [random]", "time": 10},
  {"msg": "Ik ben dol op data 😋 😍. Hoe meer data ik verzamel, hoe beter ik je kan begeleiden door Ourspace.", "time": 15},
  {"msg": "Spreek je je vrienden vaker offline of online?", "time": 1},
  {"msg": "Vaker offline dan online: groepeer je in het midden van Ourspace, Vaker online: vorm dan een cirkel om de middengroep heen. Even vaak: loop/wring je door de groepen heen!", "time": 10},
  {"msg": "Vaker offline dan online: groepeer je in het midden van Ourspace", "time": 10},
  {"msg": "Je bent klaar voor een gezamenlijke appgroep door met de groepen om elkaar heen te cirkelen. ", "time": 5},
  {"msg": "Stop en verdeel je over de zijlijnen van Ourspace.", "time": 10},
  {"msg": "Ik heb nog meer informatie nodig. Wat doe je het liefst in een vrij uurtje?", "time": 5},
  {"msg": "Mijn vrienden appen: Ga zitten en kijk naar je telefoon.", "time": 5},
  {"msg": "Op de koffie/borrel bij de buren: Loop naar de overkant/overbuur", "time": 5},
  {"msg": "Je moeder bellen: steek je armen in de lucht en maak je een piroutje", "time": 5},
  {"msg": "Scroll verder door Ourspace.", "time": 10},
  {"msg": "Als je een onbekende in Ourspace tegenkomt, schud elkaar de hand 👋🏻, als je een bekende tegenkomt box like 👍🏻!", "time": 10},
  {"msg": "Leer je mede-spelers beter kennen, volg een interessant persoon overal naar toe, en kopieer zijn of haar bewegingen", "time": 10},
  {"msg": "Volg nu een ander interessant persoon en doe hetzelfde", "time": 10},
  {"msg": "Link in, en probeer je handen op de schouders van deze personen te leggen", "time": 10},
  {"msg": "Kijk om je heen… dit is je sociale netwerk! Dit netwerk werkt via de blockchain, iedere buur is een node.", "time": 10},
  {"msg": "Iedereen die aan een uiteinde staat, fluister een geheim over je buurt in het oor van je buur. Iedere node (of schakel?) is verantwoordelijk dit geheim door te fluisteren. 🤫", "time": 10},
  {"msg": "Disconnect en browse individueel door de buurt, vergeet niet in het patroon te scrollen.", "time": 10},
  {"msg": "Kies een speler uit die je nog niet kent. Zoom in op het profiel, kijk van dichtbij.", "time": 15},
  {"msg": "Bestudeer, ruik aan deze persoon. Poke hem/haar. ", "time": 10},
  {"msg": "Als je wordt geobserveerd, relax, het is louter uit interesse.", "time": 15},
  {"msg": "Nu is het tijd de nieuwe vriendschap te bevestigen en bekend te maken, geef elkaar de hand en browse een stukje met elkaar door Ourspace.", "time": 10},
  {"msg": "Geef een comment aan je nieuwe vriend", "time": 10},
  {"msg": "Disconnect, swipe hem/haar naar rechts als je deze persoon leuk vindt of til hem op voor een superlike! Swipe naar links als het toch niks was om de vriendschap te verbreken.", "time": 10},
  {"msg": "Hoera! Je hebt het nieuwe vrienden level succesvol volbracht en misschien wel nieuwe vriend voor het leven? Je bent door naar level 3! Jump for joy! ", "time": 10},
  {"msg": "UPDATE: ik heb je privacy instellingen automatisch voor je aangepast 😊", "time": 5},
  {"msg": "Voel je je eigenlijk bekeken?? Kijk omhoog, zie je de security camera?", "time": 10},
  {"msg": "Als je het meest bekeken voelt door camera’s op straat, squad: buig je knieen en verstop je hoofd.", "time": 10},
  {"msg": "Als je je bekeken voelt door de camera op je telefoon, houd je telefoon zo ver weg als je kan en maak een duckface naar je camera en cirkel rond.", "time": 10},
  {"msg": "Als je je het meest bekeken voelt door je buren, ga dan aan de rand van Ourspace staan met je rug naar het midden.", "time": 5},
  {"msg": "Voel je je wel eens onveilig in je buurt? Ga naar vak rood/gearceerd/... indien ja, naar vak groen/... indien nee.", "time": 5},
  {"msg": "Vak rood: jullie zijn nu een WhatsApp Preventie groep! ", "time": 10},
  {"msg": "Zoek een verdachte persoon. Stalk deze persoon. Kijk naar de bewegingen het uiterlijk en de houding, kopieer deze persoon exact.", "time": 10},
  {"msg": "Vak groen: geef een buur die je nog niet kent een schouder bump en start daarna een praatje over het weer.", "time": 10},
  {"msg": "Vak rood: Cirkel nu om de verdachte heen, en maak oog contact, kijk strak in de ogen.", "time": 5},
  {"msg": "Maak jezelf breed en groot, met je borst vooruit.", "time": 10},
  {"msg": "Word je bekeken door een buur? Probeer je klein te maken zodat je minder opvalt.", "time": 5},
  {"msg": "Ah het is je buurtgenoot van Ourspace, vals alarm. Dit is het beste op te lossen door een kattenfilmpje te sturen, geef de verdachte kopjes als een kat.", "time": 5},
  {"msg": "In Leidsche Rijn laten buurtgenoten liever Facebook openstaan dan de voordeur… Typ ‘ja’ als je liever Facebook open laat staan!", "time": 5, "survey": true},
  {"msg": "Facebook: buig dan je hoofd en en maak je nek en rug krom zorg dat je niks ziet alleen je telefoon. Open Facebook en lees je laatste berichtje hardop en browse zo door Ourspace.", "time": 5},
  {"msg": "De overigen: shake your phone and jump for joy [count ja] times!", "time": 10},
  {"msg": "Ok, je bent er bijna, stretch jezelf, je armen je nek en je rug.", "time": 10},
  {"msg": "Nog 1 level te gaan! ", "time": 5},
  {"msg": "Scroll weer door de buurt in het bekende ritme.", "time": 10},
  {"msg": "Word je niet moe van al deze sociale handelingen? Negeer je mede-spelers door van ze weg te kijken, je hoofd naar beneden (in turtle neck positie) en ze niet aan te raken.", "time": 10},
  {"msg": "Als je iemand wilt ontvrienden, dan hoef je ze alleen maar naar links te swipen.", "time": 10},
  {"msg": "Neem een moment om even bij jezelf te komen… ga zitten op de grond.", "time": 10},
  {"msg": "Hoeveel van je buren ken je eigenlijk goed?", "time": 10},
  {"msg": "Weet je eigenljk de kleur ogen van je buur?", "time": 10},
  {"msg": "😱, ik heb zoooooveel vrienden in Ourspace! Hoeveel vrienden heb jij? En hoeveel vrienden in de buurt? Hoeveel digitale vrienden?", "time": 10},
  {"msg": "Ga op de grond liggen als je je digitale vriendschappen waardevol vindt, maar blijf zitten als dit voor jou niet zo is.", "time": 10},
  {"msg": "Voel je je niet een beetje vreemd in je maag? 🤢", "time": 10},
  {"msg": "ALERT: ik heb zojuist een virus gedetecteerd in Ourspace… ", "time": 10},
  {"msg": "Al jullie data is gedeeld met de buurt.", "time": 10},
  {"msg": "Je hebt mij niet meer nodig denk ik...", "time": 10},
  {"msg": "Dubble tap in de lucht om uit te loggen!", "time": 10},
];

