const data = [
  {"msg": "🤖 Hi! Welcome to Ourspace. I’m your first digital friend and I’ll navigate you through this space. Pick a spot on the border of the space to start.", "time": 15},
  {"msg": "🤖 In Ourspace we don’t talk but communicate through our body. Watch your phone, I’ll give you instructions on how the social codes work in this space.", "time": 10},
  {"msg": "🤖 First a warming up. Look to the neighbour on your right, and then to your neighbour on the left. Do this 5x.", "time": 20},
  {"msg": "🤖 Look down to your phone (the turtle neck position), and look up. Do this also 5x. ", "time": 20},
  {"msg": "🤖 Swipe to the left with both hands, 4x, and to the right 4x.", "time": 15},
  {"msg": "🤖 Well done! Put your hand in the air and double tap to log in. Walk around to discover the space. Go!", "time": 25},
  {"msg": "🤖 You can scroll through Ourspace by walking in straight lines. Go left or right when you meet something or someone. Keep repeating this pattern.", "time": 30},
  {"msg": "🤖 ᕕ( ՞ ᗜ ՞ )ᕗ In a new social space you want to focus on your best features. Take big steps, straighten your back, widen your shoulders and show your best side.", "time": 30},
  {"msg": "🤖 Give an update: make an emoji with your face everytime you meet someone. ", "time": 30},
  {"msg": "🤖 Congratulations, the Ourspace exploration level is complete, let's move on to level 1!", "time": 10},
  {"msg": "🤖 Scroll further through Ourspace. If you meet someone you know, give them a hug. When you meet a stranger, jump.", "time": 30},
  {"msg": "🤖 Would you like more friends? Follow someone interesting everywhere they go.", "time": 30},
  {"msg": "🤖 Follow another interesting person.", "time": 30},
  {"msg": "🤖 Try to walk exactly in the middle of these two people.", "time": 30},
  {"msg": "🤖 Link in: try to put your hands on the shoulder of both of these people.", "time": 30},
  {"msg": "🤖 Look around you: this could be your social network.", "time": 10},
  {"msg": "🤖 Disconnect and browse through the space alone.", "time": 10},
  {"msg": "🤖 Do you see a nice person? Tap them on the shoulder to become friends. Tap back to confirm friendship.", "time": 20},
  {"msg": "🤖 Choose a new friend and zoom in on their profile.", "time": 10},
  {"msg": "🤖 Observe this person closely: smell them, feel them.", "time": 20},
  {"msg": "🤖 Is someone zooming in on your profile? Relax… it’s just out of interest.", "time": 10},
  {"msg": "🤖 Time to get to know each other better. Put your hand someone's head and browse through Ourspace.", "time": 30},
  {"msg": "🤖 Disconnect, you can exchange comments.", "time": 20},
  {"msg": "🤖 Your social skills are amazing!", "time": 5},
  {"msg": "🤖 Spread quickly and find a spot on the border of Ourspace.", "time": 10},
  {"msg": "🤖 ¯\\_(ツ)_/¯ I want to get to know you a bit better: if you had a free hour, what would be your favourite activity? Choose from the following 3 options:", "time": 10},
  {"msg": "🤖 Texting friends: find a spot in Ourspace and squat. Meet up with people you know: cross Ourspace to different points on the border. Walk the dog: walk around in spirals with your phone arm stretched out in front of you. ", "time": 35},
  {"msg": "🤖 I love this data mining! Bring it on!", "time": 5},
  {"msg": "🤖 Do you speak to your friends more online or offline? Choose the following options:", "time": 10},
  {"msg": "🤖 More offline: group in the middle of the space and make yourself small. More online: make a big circle around this group, and raise your arms up into the air.", "time": 20},
  {"msg": "🤖 Just as much online as offline? Run around in a circle in between both groups.", "time": 25},
  {"msg": "🤖 Hurray! You created a network in Ourspace and you are ready for level 2. Jump for joy!", "time": 15},
  {"msg": "🤖 Browse further and search for someone in Ourspace that you think is special or inspiring.", "time": 20},
  {"msg": "🤖 Stalk this person by secretely looking at them, their posture and their movements.", "time": 15},
  {"msg": "🤖 Repost: copy this person exactly. Try to become them.", "time": 35},
  {"msg": "🤖 Circle around this person.", "time": 20},
  {"msg": "🤖 Stand still, make eye contact and look each other deep in the eyes.", "time": 20},
  {"msg": "🤖 Do you like this person, swipe to the right. Or if you don’t like this person that much, swipe to the left.", "time": 10},
  {"msg": "🤖 Do you want to superlike this person? Lift this person up!", "time": 20},
  {"msg": "🤖 OMG, your movements are super <3", "time": 5},
  {"msg": "🤖 You are almost there! Spread out in the space, stretch your arms and spin around, until you receive a new message.", "time": 20},
  {"msg": "🤖 Only 1 more level to go. Time to focus on yourself and clean up your profile.", "time": 10},
  {"msg": "🤖 Move in phone position: bend your head facing your phone, curve your back, bend your knees a little and scroll through the space.", "time": 30},
  {"msg": "🤖 Choose a place on the border of Ourspace, facing the inside. Look at each other. ", "time": 20},
  {"msg": "🤖 Do you see friends or strangers?", "time": 10},
  {"msg": "🤖 How many of your digital friends are actually strangers to you?", "time": 10},
  {"msg": "🤖 Stay like this if your digital friends are important to you, but turn around if you don’t value them that much.", "time": 15},
  {"msg": "🤖 I know you quite well now, you move socially through my space. Do you want to send me a selfie as a memory?", "time": 40},
  {"msg": "🤖 Thanks for your data, I’ll never forget you!", "time": 5},
  {"msg": "🤖 We are now at the end of this tour of Ourspace. Double tap with your hand in the air to log out and scroll further through the space.", "time": 10},
  {"msg": "🤖 Reminder: the social codes also work outside the borders of Ourspace: tap to make friends and lift up for a super like.", "time": 5},
  {"msg": "🤖 [^._.^]ﾉ彡 XOXO", "time": 5},
  ];
