const data = [
  {"msg": "🤖 Hi! Welkom in Ourspace. Ik ben hier je eerste digitale vriend en zal je door deze ruimte navigeren. Ga op de grenslijnen staan van Ourspace om te beginnen", "time": 10},
  {"msg": "🤖 In Ourspace communiceren we via ons lichaam. Je leert elkaar kennen door middel van fysieke acties. Praat niet en let op je telefoon, ik geef je instructies hoe de sociale gedragscodes werken!", "time": 10},
  {"msg": "🤖 Eerst een warming up. Beweeg je hoofd naar voren, cirkel je hoofd daarna 2 keer naar links.", "time": 20},
  {"msg": "🤖 Cirkel nu je hoofd 2 keer naar rechts.", "time": 20},
  {"msg": "🤖 Draai je polsen rond, 3 keer rechts, 3 keer links.", "time": 20},
  {"msg": "🤖 Goed! Steek je hand in de lucht en double tap om in te loggen, wandel door Ourspace om de ruimte te verkennen. Go!", "time": 20},
  {"msg": "🤖 Je scrollt door Ourspace door in rechte lijnen te lopen. Sla links óf rechts af wanneer je de grens of een persoon tegenkomt. Blijf dit patroon herhalen. ", "time": 30},
  {"msg": "🤖 Als je in een nieuwe sociale ruimte bent wil je dat je beste features naar voren komen. Neem grote stappen, maak je rug recht, je schouders breed en toon je beste kant ᕕ( ՞ ᗜ ՞ )ᕗ", "time": 30},
  {"msg": "🤖 Geef een update: maak een emoji met je gezicht, telkens als je iemand tegenkomt.", "time": 30},
  {"msg": "🤖 Gefeliciteerd! Je hebt de Ourspace tutorial goed volbracht en bent klaar voor level 2.", "time": 10},
  {"msg": "🤖 Scroll verder door Ourspace. Kom je een bekende tegen, geef een hug. Ontmoet je een vreemdeling, maak dan een sprongetje. ", "time": 30},
  {"msg": "🤖 Wil je meer vrienden? Volg een interessant persoon overal naartoe.", "time": 30},
  {"msg": "🤖 Volg nu een ander interessant persoon.", "time": 30},
  {"msg": "🤖 Loop nu precies in het midden van deze 2 personen.", "time": 30},
  {"msg": "🤖 Link in: probeer je handen op de schouders van deze 2 personen te leggen.", "time": 40},
  {"msg": "🤖 Kijk om je heen: dit zou je sociale netwerk kunnen zijn.", "time": 20},
  {"msg": "🤖 Disconnect en browse individueel door de ruimte.", "time": 10},
  {"msg": "🤖 Zie je een leuk persoon, tap deze op de schouder om vrienden te worden. Word je getapt, tap terug om de vriendschap te accepteren.", "time": 20},
  {"msg": "🤖 Kies een nieuwe vriend uit en zoom in op het profiel. Observeer van heel dichtbij: ruik deze persoon en voel deze persoon.", "time": 30},
  {"msg": "🤖 Als je wordt geobserveerd; relax..., het is louter uit interesse.", "time": 10},
  {"msg": "🤖 Tijd om elkaar nog iets beter te leren kennen. Leg je hand op elkaars hoofd en browse een stukje met elkaar door Ourspace.", "time": 30},
  {"msg": "🤖 Disconnect, je mag elkaar een comment geven.", "time": 20},
  {"msg": "🤖 Je sociale bewegingsskills zijn super: ga zo door!", "time": 10},
  {"msg": "🤖 Verspreid je snel over de grenzen van Ourspace.", "time": 20},
  {"msg": "🤖 Ik wil graag wat meer over je te weten komen, wat doe jij het liefste in een vrij uurtje? ¯\_(ツ)_/¯  Kies uit de volgende 3 opties:", "time": 5},
  {"msg": "🤖 Appen met vrienden: squat en blijf naar je telefoon kijken. Afspreken met bekenden: loop naar de overkant. De hond uitlaten: loop slingerend door Ourspace met je telefoonarm ver voor je uitgestrekt.", "time": 40},
  {"msg": "🤖 Wat heerlijk deze data mining! Bring it on!", "time": 20},
  {"msg": "🤖 Spreek jij je vrienden vaak offline? Groepeer je in het midden van de ruimte. Vaker online? Maak een cirkel om de groep heen en squat.", "time": 10},
  {"msg": "🤖 Heb je even vaak online als offline contact? Loop in een cirkel tussen de middengroep en de squatters.", "time": 20},
  {"msg": "🤖 Hoera! Je hebt het level succesvol volbracht en een netwerk in Ourspace opgebouwd. Je bent door naar level 3! Jump for joy!", "time": 20},
  {"msg": "🤖 Browse lekker verder en zoek iemand in Ourspace die je bijzonder of inspirerend vindt.", "time": 20},
  {"msg": "🤖 Stalk deze persoon, kijk stiekem naar het uiterlijk, observeer het postuur en de bewegingen. ", "time": 30},
  {"msg": "🤖 Kopieer deze persoon exact... Probeer hem of haar te worden.", "time": 30},
  {"msg": "🤖 Cirkel nu om deze persoon heen.", "time": 20},
  {"msg": "🤖 Maak oogcontact en kijk elkaar diep in de ogen.", "time": 30},
  {"msg": "🤖 Vind je deze persoon leuk, swipe dan naar rechts. Vind je het toch niks, swipe dan naar links.", "time": 20},
  {"msg": "🤖 Wil je een super like geven? Til deze persoon dan op.", "time": 20},
  {"msg": "🤖 Je bewegingen zijn super. Ik voel je!", "time": 10},
  {"msg": "🤖 Je bent er bijna, stretch it out! Je rug armen en je nek.", "time": 20},
  {"msg": "🤖 Verspreid je door de ruimte en draai met gestrekte armen om je as totdat je een nieuw bericht ontvangt.", "time": 20},
  {"msg": "🤖 Nog 1 level te gaan. Tijd om tot jezelf te komen en je profiel op te schonen. ", "time": 10},
  {"msg": "🤖 Neem de telefoonpositie aan: buig je hoofd naar je telefoon, krom je rug, buig je knieën een beetje en scroll door de ruimte.", "time": 30},
  {"msg": "🤖 Kies een plek op de grens van Ourspace, sta met je gezicht naar binnen. Kijk naar elkaar.", "time": 20},
  {"msg": "🤖 Zie je nu vrienden of vreemdelingen? ", "time": 10},
  {"msg": "🤖 Hoeveel van je digitale vrienden zijn eigenlijk vreemdelingen voor jou? ", "time": 10},
  {"msg": "🤖 Kun je je een leven voorstellen zonder digitale vriendschappen?", "time": 10},
  {"msg": "🤖 Blijf staan als je digitale vrienden belangrijk voor je zijn, draai je om met je gezicht naar buiten wanneer je hier minder waarde aan hecht.", "time": 20},
  {"msg": "🤖 Ik ken je nu best goed, je beweegt je heel sociaal door mijn ruimte. Stuur je me een selfie ter herinnering?", "time": 20},
  {"msg": "🤖 Bedankt voor je vertrouwen, ik zal je data nooit vergeten.", "time": 10},
  {"msg": "🤖 Double tap met je hand in de lucht om uit te loggen en scroll verder door RAUM.", "time": 10}
];
