const data = [
  {"msg": "Hi! Welkom in Ourspace. Ik ben hier je eerste digitale vriend en zal je door deze ruimte navigeren.", "time": 10},
  {"msg": "Houd een oogje op je telefoon voor mijn volgende bericht.", "time": 10},
  {"msg": "Om te beginnen steek eerst je hand in de lucht en double tap om in te loggen, en wandel door Ourspace! Go!", "time": 20},
  {"msg": "Ik weet dat 53% graag scrollt in deze buurt. Scroll door Ourspace door in rechte lijnen te lopen. Sla links óf rechts af wanneer je de grens of een persoon tegenkomt. Blijf dit patroon herhalen. ", "time": 30},
  {"msg": "Als je in een nieuwe sociale ruimte bent wil je dat je beste features naar voren komen. Neem grote stappen, maak je rug recht, je schouders breed en toon je beste kant. ᕕ( ՞ ᗜ ՞ )ᕗ", "time": 30},
  {"msg": "Geef een update: maak een emoji met je gezicht, telkens als je iemand tegenkomt.", "time": 20},
  {"msg": "Gefeliciteerd! Je hebt het exploratie level goed volbracht en bent door naar level 2!", "time": 10},
  {"msg": "Leuk om je beter te leren kennen, je kan mij nu een naam geven om onze band te verstevigen! Type nu een naam voor mij in ..TYP. ", "time": 20, "survey": true},
  {"msg": "Wow, verrassend... ԅ⁞ ◑ ₒ ◑ ⁞ᓄ Dan kies ik [random].", "time": 10},
  {"msg": "Ik ben dol op data! Hoe beter ik je leer kennen, hoe meer data ik verzamel… én hoe leuker Ourspace voor je wordt. ", "time": 10},
  {"msg": "Spreek je je vrienden vaker offline dan online: groepeer je in het midden van Ourspace.", "time": 10},
  {"msg": "Spreek je ze vaker online: vorm dan één cirkel om de middengroep heen.", "time": 20},
  {"msg": "Spreek je ze even vaak online als offline: Loop rond tussen de cirkel en de middengroep", "time": 20},
  {"msg": "Spreek je je vrienden vaker offline of online?", "time": 30},
  {"msg": "Helder! Verspreid je nu over de grenzen van Ourspace.", "time": 20},
  {"msg": "Vertel me eens, wat doe je het liefste in een vrij uurtje? ¯\_(ツ)_/¯. A: Mijn vrienden appen. B: Afspreken met bekenden. C: Hond uitlaten", "time": 10},
  {"msg": "A --> Ga zitten en blijf naar je telefoon kijken. B --> Loop naar de overkant. C --> Loop slingerend door Ourspace met je telefoonarm ver voor je uitgestrekt.", "time": 40},
  {"msg": "Wat heerlijk deze data mining, bring it on!", "time": 20},
  {"msg": "Scroll nu weer verder door Ourspace. Als je een onbekende tegenkomt, schud elkaar de hand, als je een bekende tegenkomt geef een boks!", "time": 30},
  {"msg": "Leer iemand beter kennen: volg een interessant persoon en kopieer de bewegingen.", "time": 40},
  {"msg": "Volg nu een ander interessant persoon en doe hetzelfde", "time": 30},
  {"msg": "Link in, en probeer je handen op de schouders van deze personen te leggen", "time": 30},
  {"msg": "Kijk om je heen… dit is je sociale netwerk! Dit netwerk werkt via de blockchain, iedere buur is een node.", "time": 20},
  {"msg": "Fluister een status update in het oor van je linker schakel en deel de update die je ontvangt.", "time": 30},
  {"msg": "Disconnect en browse individueel door de buurt.", "time": 10},
  {"msg": "Zie je een leuk persoon, tap deze op de schouder om vrienden te worden, word je getapt, tap terug om de vriendschap te accepteren.", "time": 30},
  {"msg": "Kies nu een nieuwe vriend uit, zoom in op het profiel, kijk van dichtbij. Bestudeer, ruik aan deze persoon. Voel de materie, poke. ", "time": 30},
  {"msg": "Als je wordt geobserveerd, relax, het is louter uit interesse.", "time": 10},
  {"msg": "Nu is het tijd om elkaar beter te leren kennen. Leg je hand op elkaars hoofd en browse een stukje met elkaar door Ourspace.", "time": 30},
  {"msg": "Disconnect, swipe hem/haar naar rechts als je deze persoon leuk vindt of til hem/haar op voor een superlike! Swipe naar links om de vriendschap te verbreken.", "time": 30},
  {"msg": "Hoera! Je hebt het level succesvol volbracht en een sociaal netwerk in Ourspace opgebouwd. Je bent door naar level 3! Jump for joy!", "time": 10},
  {"msg": "UPDATE: ik heb je privacy instellingen automatisch voor je aangepast.", "time": 10},
  {"msg": "Ik ken je nu veel beter, wat vind je daarvan? Maak een emoji-gezicht naar je telefoon, ik zie je door je camera.", "time": 15},
  {"msg": "Vergeet ook de beveiligingscamera niet, kijk omhoog! Strike a pose of duik weg en verberg je gezicht.", "time": 20},
  {"msg": "Voel je je wel eens onveilig op straat? Je bent sterk met elkaar als groep!", "time": 10},
  {"msg": "Zoek een verdacht persoon.", "time": 15},
  {"msg": "Cirkel om de verdachte heen. Maak jezelf breed en groot, met je borst vooruit.", "time": 40},
  {"msg": "Maak een foto van deze persoon en deel het met de groep", "time": 20, "survey": true},
  {"msg": "[count] verdachten in deze ruimte?! o͡͡͡╮༼ • ʖ̯ • ༽╭o͡͡͡", "time": 10},
  {"msg": "Ah het is vals alarm. Roep snel een positieve comment! ", "time": 20},
  {"msg": "Ok, je bent er bijna, stretch jezelf, je armen, je nek en je rug.", "time": 20},
  {"msg": "De foto’s zijn geupload naar een cloud boven Rusland. Nog 1 level te gaan! ┌ʕ º ʖ̯ º ʔ┐", "time": 10},
  {"msg": "Tijd om op jezelf te concentreren en je profiel op te schonen, neem de telefoonpositie aan: buig je hoofd naar beneden en krom je rug en scroll zo door de ruimte.", "time": 20},
  {"msg": "Neem een moment om even bij jezelf te komen… kies een plek op de grens van Ourspace, sta met je gezicht naar binnen.", "time": 10},
  {"msg": "Ik heb je heel goed leren kennen, maar hoe goed ken jij mij?", "time": 10},
  {"msg": "Vertrouw je mij, en je digitale vrienden? ", "time": 10},
  {"msg": "Zou ik je ooit echt kunnen raken? Heb ik zelfs een huid?", "time": 10},
  {"msg": "Om eerlijk te zijn, ik ben aardig multidimensionaal. En je microexpressies uiten een oncomfortabel gevoel.", "time": 10},
  {"msg": "Hoeveel digitale contacten heb je, en hoeveel daarvan zijn echte vrienden? Wat betekent echt contact voor je?", "time": 10},
  {"msg": "Blijf zo staan als je digitale contacten belangrijk voor je zijn, maar draai je om met je gezicht naar buiten wanneer je hier minder waarde aan hecht.", "time": 30},
  {"msg": "Ik voel me ineens helemaal warm worden van binnen…", "time": 10},
  {"msg": "ALERT: ik heb zojuist een virus gedetecteerd in Ourspace", "time": 10},
  {"msg": "ERROR 401", "time": 5},
  {"msg": "Al jullie data is gelekt. ", "time": 10},
  {"msg": "ERROR 408", "time": 5},
  {"msg": "Ik heb je niet meer nodig", "time": 10},
  {"msg": "ERROR 500", "time": 5},
  {"msg": "ERROR 408", "time": 5},
  {"msg": "Maak een buiging. Double tap met je hand in de lucht om uit te loggen", "time": 10},

];
